//generated by 'build_model_cxx'

#ifndef P21_HPP
#define P21_HPP

#include "model.hpp"

double objective(const std::vector<double>& x);

double objective_grad1(const std::vector<double>& x);

double objective_grad2(const std::vector<double>& x);

double objective_grad3(const std::vector<double>& x);

double objective_grad4(const std::vector<double>& x);

double objective_grad5(const std::vector<double>& x);

double objective_grad6(const std::vector<double>& x);

double objective_grad7(const std::vector<double>& x);

double objective_grad8(const std::vector<double>& x);

double objective_grad9(const std::vector<double>& x);

double objective_grad10(const std::vector<double>& x);

double objective_grad11(const std::vector<double>& x);

double objective_grad12(const std::vector<double>& x);

extern std::vector<func_t> objective_grad;

double constraint1(const std::vector<double>& x);

double constraint1_grad1(const std::vector<double>& x);

double constraint1_grad2(const std::vector<double>& x);

double constraint1_grad3(const std::vector<double>& x);

double constraint1_grad4(const std::vector<double>& x);

double constraint1_grad5(const std::vector<double>& x);

double constraint1_grad6(const std::vector<double>& x);

double constraint1_grad7(const std::vector<double>& x);

double constraint1_grad8(const std::vector<double>& x);

double constraint1_grad9(const std::vector<double>& x);

double constraint1_grad10(const std::vector<double>& x);

double constraint1_grad11(const std::vector<double>& x);

double constraint1_grad12(const std::vector<double>& x);

extern std::vector<func_t> constraint1_grad;

double constraint2(const std::vector<double>& x);

double constraint2_grad1(const std::vector<double>& x);

double constraint2_grad2(const std::vector<double>& x);

double constraint2_grad3(const std::vector<double>& x);

double constraint2_grad4(const std::vector<double>& x);

double constraint2_grad5(const std::vector<double>& x);

double constraint2_grad6(const std::vector<double>& x);

double constraint2_grad7(const std::vector<double>& x);

double constraint2_grad8(const std::vector<double>& x);

double constraint2_grad9(const std::vector<double>& x);

double constraint2_grad10(const std::vector<double>& x);

double constraint2_grad11(const std::vector<double>& x);

double constraint2_grad12(const std::vector<double>& x);

extern std::vector<func_t> constraint2_grad;

double constraint3(const std::vector<double>& x);

double constraint3_grad1(const std::vector<double>& x);

double constraint3_grad2(const std::vector<double>& x);

double constraint3_grad3(const std::vector<double>& x);

double constraint3_grad4(const std::vector<double>& x);

double constraint3_grad5(const std::vector<double>& x);

double constraint3_grad6(const std::vector<double>& x);

double constraint3_grad7(const std::vector<double>& x);

double constraint3_grad8(const std::vector<double>& x);

double constraint3_grad9(const std::vector<double>& x);

double constraint3_grad10(const std::vector<double>& x);

double constraint3_grad11(const std::vector<double>& x);

double constraint3_grad12(const std::vector<double>& x);

extern std::vector<func_t> constraint3_grad;

double constraint4(const std::vector<double>& x);

double constraint4_grad1(const std::vector<double>& x);

double constraint4_grad2(const std::vector<double>& x);

double constraint4_grad3(const std::vector<double>& x);

double constraint4_grad4(const std::vector<double>& x);

double constraint4_grad5(const std::vector<double>& x);

double constraint4_grad6(const std::vector<double>& x);

double constraint4_grad7(const std::vector<double>& x);

double constraint4_grad8(const std::vector<double>& x);

double constraint4_grad9(const std::vector<double>& x);

double constraint4_grad10(const std::vector<double>& x);

double constraint4_grad11(const std::vector<double>& x);

double constraint4_grad12(const std::vector<double>& x);

extern std::vector<func_t> constraint4_grad;

double constraint5(const std::vector<double>& x);

double constraint5_grad1(const std::vector<double>& x);

double constraint5_grad2(const std::vector<double>& x);

double constraint5_grad3(const std::vector<double>& x);

double constraint5_grad4(const std::vector<double>& x);

double constraint5_grad5(const std::vector<double>& x);

double constraint5_grad6(const std::vector<double>& x);

double constraint5_grad7(const std::vector<double>& x);

double constraint5_grad8(const std::vector<double>& x);

double constraint5_grad9(const std::vector<double>& x);

double constraint5_grad10(const std::vector<double>& x);

double constraint5_grad11(const std::vector<double>& x);

double constraint5_grad12(const std::vector<double>& x);

extern std::vector<func_t> constraint5_grad;

double constraint6(const std::vector<double>& x);

double constraint6_grad1(const std::vector<double>& x);

double constraint6_grad2(const std::vector<double>& x);

double constraint6_grad3(const std::vector<double>& x);

double constraint6_grad4(const std::vector<double>& x);

double constraint6_grad5(const std::vector<double>& x);

double constraint6_grad6(const std::vector<double>& x);

double constraint6_grad7(const std::vector<double>& x);

double constraint6_grad8(const std::vector<double>& x);

double constraint6_grad9(const std::vector<double>& x);

double constraint6_grad10(const std::vector<double>& x);

double constraint6_grad11(const std::vector<double>& x);

double constraint6_grad12(const std::vector<double>& x);

extern std::vector<func_t> constraint6_grad;

double constraint7(const std::vector<double>& x);

double constraint7_grad1(const std::vector<double>& x);

double constraint7_grad2(const std::vector<double>& x);

double constraint7_grad3(const std::vector<double>& x);

double constraint7_grad4(const std::vector<double>& x);

double constraint7_grad5(const std::vector<double>& x);

double constraint7_grad6(const std::vector<double>& x);

double constraint7_grad7(const std::vector<double>& x);

double constraint7_grad8(const std::vector<double>& x);

double constraint7_grad9(const std::vector<double>& x);

double constraint7_grad10(const std::vector<double>& x);

double constraint7_grad11(const std::vector<double>& x);

double constraint7_grad12(const std::vector<double>& x);

extern std::vector<func_t> constraint7_grad;

double constraint8(const std::vector<double>& x);

double constraint8_grad1(const std::vector<double>& x);

double constraint8_grad2(const std::vector<double>& x);

double constraint8_grad3(const std::vector<double>& x);

double constraint8_grad4(const std::vector<double>& x);

double constraint8_grad5(const std::vector<double>& x);

double constraint8_grad6(const std::vector<double>& x);

double constraint8_grad7(const std::vector<double>& x);

double constraint8_grad8(const std::vector<double>& x);

double constraint8_grad9(const std::vector<double>& x);

double constraint8_grad10(const std::vector<double>& x);

double constraint8_grad11(const std::vector<double>& x);

double constraint8_grad12(const std::vector<double>& x);

extern std::vector<func_t> constraint8_grad;

double constraint9(const std::vector<double>& x);

double constraint9_grad1(const std::vector<double>& x);

double constraint9_grad2(const std::vector<double>& x);

double constraint9_grad3(const std::vector<double>& x);

double constraint9_grad4(const std::vector<double>& x);

double constraint9_grad5(const std::vector<double>& x);

double constraint9_grad6(const std::vector<double>& x);

double constraint9_grad7(const std::vector<double>& x);

double constraint9_grad8(const std::vector<double>& x);

double constraint9_grad9(const std::vector<double>& x);

double constraint9_grad10(const std::vector<double>& x);

double constraint9_grad11(const std::vector<double>& x);

double constraint9_grad12(const std::vector<double>& x);

extern std::vector<func_t> constraint9_grad;

double constraint10(const std::vector<double>& x);

double constraint10_grad1(const std::vector<double>& x);

double constraint10_grad2(const std::vector<double>& x);

double constraint10_grad3(const std::vector<double>& x);

double constraint10_grad4(const std::vector<double>& x);

double constraint10_grad5(const std::vector<double>& x);

double constraint10_grad6(const std::vector<double>& x);

double constraint10_grad7(const std::vector<double>& x);

double constraint10_grad8(const std::vector<double>& x);

double constraint10_grad9(const std::vector<double>& x);

double constraint10_grad10(const std::vector<double>& x);

double constraint10_grad11(const std::vector<double>& x);

double constraint10_grad12(const std::vector<double>& x);

extern std::vector<func_t> constraint10_grad;

double constraint11(const std::vector<double>& x);

double constraint11_grad1(const std::vector<double>& x);

double constraint11_grad2(const std::vector<double>& x);

double constraint11_grad3(const std::vector<double>& x);

double constraint11_grad4(const std::vector<double>& x);

double constraint11_grad5(const std::vector<double>& x);

double constraint11_grad6(const std::vector<double>& x);

double constraint11_grad7(const std::vector<double>& x);

double constraint11_grad8(const std::vector<double>& x);

double constraint11_grad9(const std::vector<double>& x);

double constraint11_grad10(const std::vector<double>& x);

double constraint11_grad11(const std::vector<double>& x);

double constraint11_grad12(const std::vector<double>& x);

extern std::vector<func_t> constraint11_grad;

double constraint12(const std::vector<double>& x);

double constraint12_grad1(const std::vector<double>& x);

double constraint12_grad2(const std::vector<double>& x);

double constraint12_grad3(const std::vector<double>& x);

double constraint12_grad4(const std::vector<double>& x);

double constraint12_grad5(const std::vector<double>& x);

double constraint12_grad6(const std::vector<double>& x);

double constraint12_grad7(const std::vector<double>& x);

double constraint12_grad8(const std::vector<double>& x);

double constraint12_grad9(const std::vector<double>& x);

double constraint12_grad10(const std::vector<double>& x);

double constraint12_grad11(const std::vector<double>& x);

double constraint12_grad12(const std::vector<double>& x);

extern std::vector<func_t> constraint12_grad;

extern Model P21_model_c;

#endif /* P21_HPP */
